networks:
  mvcalloptions:
    external: true

services:
  redis:
    container_name: redis
    image: redis:7.2.2-alpine
    networks:
      - mvcalloptions
    ports:
      - "6379:6379"
